### ISSUE TITLE
Use Mergify for automatically merge scala-steward's PRs?

### ISSUE THREAD

**Issue by takayahilton** [atnos-org/eff#249]
**Description**
Mergify is often used for projects that use scala-steward.

Install [Mergify app](https://github.com/apps/mergify) and write .mergify.yml like this
```yml
pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr      
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
```

If the CI is successful and the update is semver-patch, the scala-steward PR will be merged automatically.
